name: golangci-lint

on:
  pull_request:
    branches: [ team6-agent ]

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with: 
          tool_name: golangci-lint
          fail_on_error: true
          working-directory: ./internal/clients/team6/...
      - name: golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--disable-all -E golint"
          tool_name: golint 
          level: warning 
          working-directory: ./internal/clients/team6/...
