name: golangci-lint

on:
  pull_request:
    branches: [ team6-agent ]

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-20.04
    steps:
      - name: golint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--disable-all -E golint"
          tool_name: golint 
          level: warning 
          golint-path: './ingternal/client/team6/...'
